on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  style:
    name: Run StyLua
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout LLS-Addons

      # Use custom action to get submodules
      # This allows us to get submodules that live on GitLab
      - uses: dsaltares/fetch-gh-release-asset@1.1.0
        name: Get submodule fetching action
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repo: carsakiller/get-submodules-action
          file: dist.zip
          target: submodule-action.zip
      - name: Unzip submodule fetching action
        run: unzip submodule-action.zip -d submodule-action
      - uses: ./submodule-action/dist
        name: Get all submodules

      - uses: JohnnyMorganz/stylua-action@v2.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          args: --check addons
  build:
    name: Get Addon Metadata
    runs-on: ubuntu-latest
    needs: style
    if: ${{ github.event_name == 'push'}}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        name: Checkout LLS-Addons

      # Use custom action to get submodules
      # This allows us to get submodules that live on GitLab
      - uses: dsaltares/fetch-gh-release-asset@1.1.0
        name: Get submodule fetching action
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repo: carsakiller/get-submodules-action
          file: dist.zip
          target: submodule-action.zip
      - name: Unzip submodule fetching action
        run: unzip submodule-action.zip -d submodule-action
      - uses: ./submodule-action/dist
        name: Get all submodules

      # Custom action that gets metadata on each addon
      - uses: dsaltares/fetch-gh-release-asset@1.1.0
        name: Get submodule metadata fetching action
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repo: LuaLS/LLS-Addons-Action
          file: dist.zip
          target: action.zip
      - name: Unzip custom action
        run: unzip action.zip -d action
      - uses: ./action/dist
        name: Get Addon Metadata

      # Commit new metadata
      - name: Commit Metadata
        uses: stefanzweifel/git-auto-commit-action@v4.16.0
        with:
          commit_message: "chore: Update Addon Metadata"
          file_pattern: addons/*/info.json
          commit_author: github-actions[bot]
          commit_user_name: github-actions[bot]
          commit_user_email: 41898282+github-actions[bot]@users.noreply.github.com
